git_update: clean up the code

diff --git a/systemd/PKGBUILD b/systemd/PKGBUILD
--- a/systemd/PKGBUILD
+++ b/systemd/PKGBUILD
@@ -160,22 +160,24 @@ get_update() {
   | while read _line; do
       _version="${_line##*-}"
       _version="${_version%%.*}"
+
       if [[ "$_version" == "$_pkgver" ]]; then
         echo "  up-to-date: yes"
-      else
-        echo "$_version" | grep -qE '^([0-9]+)$'
-        if [[ $? -eq 0 ]]; then
-          echo "  update: 0.${_version}"
-          echo "  update.link:"
-          echo "  - ${_line}"
-          echo "  - ${_cgit_url}/snapshot/systemd-${_version}.tar.gz"
-          echo "  - ${_cgit_url}/tree/?id=v${_version}"
-          echo "  news: ${_cgit_url}/tree/NEWS?id=v${_version}"
-        else
-          echo "  error: curl.format"
-          return 1
-        fi
+        break
       fi
+
+      echo "$_version" | grep -qE '^([0-9]+)$'
+      if [[ $? -ge 1 ]]; then
+        echo "  error: curl.format"
+        return 1
+      fi
+
+      echo "  update: 0.${_version}"
+      echo "  update.link:"
+      echo "  - ${_line}"
+      echo "  - ${_cgit_url}/snapshot/systemd-${_version}.tar.gz"
+      echo "  - ${_cgit_url}/tree/?id=v${_version}"
+      echo "  news: ${_cgit_url}/tree/NEWS?id=v${_version}"
     done
 
   [[ ${PIPESTATUS[0]} -eq 0 ]] \
